#!/bin/bash

echo "=== Drone Simulation Setup and Run Script ==="

# Check if virtual environment exists
if [ ! -d "venv" ]; then
    echo "Creating virtual environment..."
    python3 -m venv venv
else
    echo "Virtual environment already exists"
fi

# Activate virtual environment and install dependencies
echo "Activating virtual environment and installing dependencies..."
source venv/bin/activate
pip install -r requirements.txt

echo ""
echo "=== Setup Complete ==="
echo ""
echo "To run the LLM service:"
echo "1. Activate the virtual environment: source venv/bin/activate"
echo "2. Run the LLM service: python services/llm/main.py"
echo ""
echo "To run Unity:"
echo "1. Open the Unity project in unity-client/drone-env/"
echo "2. Open the SampleScene or DronePlayground scene"
echo "3. Add the DroneCommandUI and SimpleHTTPServer scripts to a GameObject"
echo "4. Set up the UI elements (Canvas, InputField, Button, TextMeshPro)"
echo "5. Add a drone from the ProfessionalAssets/DronePack/Prefabs/"
echo "6. Run the scene"
echo ""
echo "Testing the system:"
echo "1. Start the LLM service (it will run on port 5006)"
echo "2. Start Unity (HTTP server will run on port 5005)"
echo "3. In Unity, press Tab to show the input panel"
echo "4. Type a command like 'fly forward' or 'turn left'"
echo "5. The drone should respond!"
echo ""
echo "Available commands:"
echo "- move_forward, move_backward, move_left, move_right"
echo "- ascend, descend"
echo "- turn_left, turn_right"
echo ""
echo ""
echo "=== Additional Setup Steps ==="
echo ""
echo "1. Install Ollama (if not already installed):"
echo "   - Download from: https://ollama.com/download"
echo "   - Run: ollama serve"
echo "   - Pull model: ollama pull llama2"
echo ""
echo "2. In Unity:"
echo "   - Open the project in unity-client/drone-env/"
echo "   - Open SampleScene"
echo "   - Add a professional drone: Assets → ProfessionalAssets → DronePack → Prefabs → _Drone [Quad]"
echo "   - Position drone at (0, 2, 0)"
echo "   - Create empty GameObject -> Add SetupDemoScene.cs"
echo "   - Right-click script -> 'Setup Complete Demo Scene'"
echo ""
echo "3. Test the system:"
echo "   - Start LLM: python services/llm/main.py"
echo "   - Start Unity scene"
echo "   - Press Tab to show UI"
echo "   - Type commands like 'fly forward' or 'turn left'"
echo ""
echo "=== System Status ==="
echo "✅ Virtual environment created"
echo "✅ Python dependencies installed"
echo "✅ Unity scripts created"
echo "✅ HTTP communication setup"
echo "✅ Professional drone integration"
echo "⚠️  Ollama needs to be installed and running separately"
echo "⚠️  Professional drone pack requires full version for all features"
